site_name: blog
site_author: Hrushikesh Dokala
repo_url: https://github.com/Hk669/blog/
site_url: https://blog.hrushikesh.xyz
# base_url: /blog/
repo_name: Hk669/blog
edit_uri: edit/main/docs
copyright: Copyright &copy; 2024 Hrushikesh Dokala
nav:
  - Home:
    - Home: 'index.md'
    - Writing: 'writing/index.md'
    - DSA: https://dsa.hrushikesh.xyz
  - Writing:
    - writing: "writing/index.md"
  - DSA: https://dsa.hrushikesh.xyz
    # - posts:
    #   - DNS: 'writing/posts/dns.md'
    #   - pydantic: 'writing/posts/pydantic.md'
    #   - visualize deep learning model: 'writing/posts/visualizedeeplearning.md'
    # - categories:
    #   - categories

theme:
  name: material
  logo: assets/hk.png
  icon:
    repo: fontawesome/brands/git-alt
  favicon: assets/hk.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default 
      primary: purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Open Sans
    code: Roboto Mono
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra:
  analytics:
    provider: google
    property: G-2E2ZC5EMHV
    feedback:
      title: Was this post helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help me improve by 
            using my <a href="..." target="_blank" rel="noopener">feedback</a>
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hrushikeshhhh
    - icon: fontawesome/brands/github
      link: https://github.com/Hk669
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/hrushikeshdokala/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/hkeshhk
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/hk669
  generator: false

plugins:
  - search
  # - social:
  #     enabled: !ENV [CI, false]
  - minify:
      minify_html: true
  - blog:
      blog_dir: writing
      blog_toc: true
      post_dir: writing/posts
      post_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      authors_file: "{blog}/.authors.yml"
  - rss:
      match_path: writing/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
      enabled: !ENV [CI, false]