site_name: hk
site_author: Hrushikesh Dokala
repo_url: https://github.com/Hk669/blog/
site_url: https://hk669.github.io/blog/
# base_url: /blog/
repo_name: Hk669/blog
edit_uri: edit/main/docs
copyright: Copyright &copy; 2024 Hrushikesh Dokala
nav:
  - Home:
    - Home: 'index.md'
    - Writing: 'writing/index.md'
  - Writing:
    - writing: "writing/index.md"
    - posts:
      - DNS: 'writing/posts/dns.md'
      - pydantic: 'writing/posts/pydantic.md'
      - visualize deep learning model: 'writing/posts/visualizedeeplearning.md'
    # - categories:
    #   - categories

theme:
  name: material
  logo: assets/logo.jpg
  icon:
    repo: fontawesome/brands/git-alt
  favicon: assets/logo.jpg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default 
      primary: purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Open Sans
    code: Open Sans
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hrushikeshhhh
    - icon: fontawesome/brands/github
      link: https://github.com/Hk669
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/hrushikeshdokala/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/hkeshhk
  generator: false
plugins:
  - search
  - rss:
      match_path: writing/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
