name: ci
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3 

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
            
      - name: Setup Cache     
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache


      - name: Install Requirements
        run: pip install -r requirements.txt
      
      - name: Build and Deploy
        run: |
          mkdocs build
          mkdocs gh-deploy --force

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs
      #     cname: blog.hrushikesh.xyz